### ISSUE TITLE
大佬，露奈雅拉的介绍部分好像有点问题

### ISSUE THREAD

**Issue by mydu27** [HsinChang/pkms#1]
原文如下：
**石盘需求：露奈雅拉的石盘得分为4分，而由于露奈雅拉而宝成为完全体————无需加减分。故得分为：1；**

文字顺序错了，几宝完全体也没看出来

**Comment by BeginnerSlob** [comment]
二宝，错别字而已（

**Comment by Si-tulao** [comment]
写错字了，改了
